[custom]


; ✅ 高优先级自定义规则（来源 IP 不走代理） 来源IP是 不走代理
; ruleset=🎯 全球直连,[]SRC-IP-CIDR,192.168.68.0/24
ruleset=🎯 全球直连,[]SRC-IP-CIDR,192.168.31.2/32
; 32 网段都不走代理 ，目前是iptv
ruleset=🎯 全球直连,[]SRC-IP-CIDR,192.168.32.0/32

ruleset=🎯 全球直连,[]IP-CIDR,192.168.68.0/24
ruleset=🎯 全球直连,[]IP-CIDR,192.168.31.0/24
ruleset=🎯 全球直连,[]IP-CIDR,192.168.32.0/24

; 自定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/happy6310/ACL4SSR/refs/heads/lx/LX_RULE_Direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/happy6310/ACL4SSR/refs/heads/lx/LX_RULE_Proxy.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/happy6310/ACL4SSR/refs/heads/lx/LX_RULE_Other.list


; 其他服务常规代理
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list

; DNS 泄露防护
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,dns.google
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list


; 🛑 广告拦截
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list





; 🎯 全球直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🎯 全球直连,[]GEOIP,LAN

; 🐟 漏网之鱼
ruleset=🐟 漏网之鱼,[]FINAL

;====================策略组设置====================
; 自动选择，所有节点不通则使用 DIRECT 兜底
custom_proxy_group=♻️ 自动选择`fallback`.*`[]DIRECT`http://www.gstatic.com/generate_204`300,,50

; 节点选择：提供自动 + 直连
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT

; 手动切换：手动选定节点
custom_proxy_group=🚀 手动切换`select`.*

; 全球直连：提供多个选择项
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; 广告拦截：拒绝或直连
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT

; 漏网之鱼：兜底 fallback
custom_proxy_group=🐟 漏网之鱼`fallback`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`http://www.gstatic.com/generate_204`300,,50

; 启用规则生成器
enable_rule_generator=true
overwrite_original_rules=true




